
package cn.poweru.api.sms.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SMS", targetNamespace = "http://webservice.sms.api.poweru.cn", wsdlLocation = "http://111.204.176.254:13839/SMSG/services/SMS?wsdl")
public class SMS
    extends Service
{

    private final static URL SMS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cn.poweru.api.sms.webservice.SMS.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cn.poweru.api.sms.webservice.SMS.class.getResource(".");
            url = new URL(baseUrl, "http://111.204.176.254:13839/SMSG/services/SMS?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://111.204.176.254:13839/SMSG/services/SMS?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SMS_WSDL_LOCATION = url;
    }

    public SMS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SMS() {
        super(SMS_WSDL_LOCATION, new QName("http://webservice.sms.api.poweru.cn", "SMS"));
    }

    /**
     * 
     * @return
     *     returns SMSPortType
     */
    @WebEndpoint(name = "SMSHttpPort")
    public SMSPortType getSMSHttpPort() {
        return super.getPort(new QName("http://webservice.sms.api.poweru.cn", "SMSHttpPort"), SMSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SMSPortType
     */
    @WebEndpoint(name = "SMSHttpPort")
    public SMSPortType getSMSHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.sms.api.poweru.cn", "SMSHttpPort"), SMSPortType.class, features);
    }

}
